# Basic Configuration
project_name: "autoaws"
environment: "dev"
aws_region: "us-east-1"

# Global Tags
common_tags:
  Owner: "DevOps Team"
  Project: "AutoAWS"
  Environment: "dev"
  ManagedBy: "terraform"

# Module Controls
enable_vpc: true
# enable_security_groups: true
# enable_ec2: true
# enable_rds: false
# enable_s3: true
# enable_cloudwatch: true
# enable_elb: false
# enable_ecs: false
# enable_ecr: false

# VPC Configuration (detailed and flexible)
vpc_cidr: "10.0.0.0/16"
enable_dns_hostnames: true
enable_dns_support: true

# Subnet Configurations (much more intuitive)
public_subnets:
  - name: "public-web-1"
    cidr_block: "10.0.1.0/24"
    availability_zone: "us-east-1a"
  - name: "public-web-2"
    cidr_block: "10.0.2.0/24"
    availability_zone: "us-east-1b"

private_subnets:
  - name: "private-app-1"
    cidr_block: "10.0.10.0/24"
    availability_zone: "us-east-1a"
    
  - name: "private-db-1"
    cidr_block: "10.0.20.0/24"
    availability_zone: "us-east-1a"

services:
  security_groups:
    - name: alb
      description: "ALB security group"
      ingress_rules:
        - from_port: 80
          to_port: 80
          protocol: tcp
          cidr_blocks: ["0.0.0.0/0"]
          description: "Allow HTTP from anywhere"
      egress_rules: []


  alb:
    create: true