name: Infra CI/CD

on:
    push:
        paths:
            - 'config/*.yaml'
    wrorkflow_dispatch:
        inputs:
            action:
                description: "Choose action: deploy or destroy"
                required: true
                default: "deploy"
                type: choice
                options:
                    - deploy
                    - destroy
                    